#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/cli/bin/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/cli/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/cli/bin/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/cli/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules/@angular/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/@angular+cli@6.0.8/node_modules:/workspaces/idiada-exercise-frontend-angular/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/ng" "$@"
else
  exec node  "$basedir/../../bin/ng" "$@"
fi
